# Directory where Opengist will store its data. Default: ~/.opengist/
opengist-home:

# Name of the SQLite database file. Default: opengist.db
db-filename: opengist.db

# Prevents the creation of new accounts (either `true` or `false`). Default: false
disable-signup: false

# Set the log level to one of the following: trace, debug, info, warn, error, fatal, panic. Default: warn
log-level: warn

# HTTP server configuration
http:

  # Host to bind to. Default: 0.0.0.0
  host: 0.0.0.0

  # Port to bind to. Default: 6157
  port: 6157

  # Domain to use in links. Default: localhost
  domain: localhost

  # Enable or disable git operations (clone, pull, push) via HTTP (either `true` or `false`). Default: true
  git-enabled: true

# SSH built-in server configuration
# Note: it is not using the SSH daemon from your machine (yet)
ssh:

  # Enable or disable SSH built-in server
  # for git operations (clone, pull, push) via SSH (either `true` or `false`). Default: true
  enabled: true

  # Host to bind to. Default: 0.0.0.0
  host: 0.0.0.0

  # Port to bind to. Default: 2222
  # Note: it cannot be the same port as the SSH daemon if it's currently running
  # If you want to use the port 22 for the built-in SSH server,
  # you can either change the port of the SSH daemon or stop it
  port: 2222

  # Domain to use in links. Default: localhost
  domain: localhost

  # Path or alias to ssh-keygen executable. Default: ssh-keygen
  keygen-executable: ssh-keygen
